In [1]:
import pandas as pd

In [2]:
job = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Datasets\JobSalary2.csv",index_col = 0)
job

      Computer  Marketing  Engineer
S_No
1         84.0       55.0        75
2         90.0       53.0        70
3         63.0        NaN        88
4          NaN       50.0        77
5         63.0       41.0        89
6         75.0       54.0        85
7          NaN       51.0        96
8         77.0       64.0       105

## Mean Imputator

In [3]:
mu = dict(job.mean())
job.fillna(mu)

       Computer  Marketing  Engineer
S_No
1     84.000000  55.000000        75
2     90.000000  53.000000        70
3     63.000000  52.571429        88
4     75.333333  50.000000        77
5     63.000000  41.000000        89
6     75.000000  54.000000        85
7     75.333333  51.000000        96
8     77.000000  64.000000       105

## Median Imputator

In [4]:
mu = dict(job.median())
job.fillna(mu)

      Computer  Marketing  Engineer
S_No
1         84.0       55.0        75
2         90.0       53.0        70
3         63.0       53.0        88
4         76.0       50.0        77
5         63.0       41.0        89
6         75.0       54.0        85
7         76.0       51.0        96
8         77.0       64.0       105

# Simple Imputer

In [5]:
from sklearn.impute import SimpleImputer

In [6]:
imputer = SimpleImputer(strategy='mean').set_output(transform='pandas') # default strategy='mean'
imputer.fit(job) # calculate statistics only
print(imputer.statistics_)
imputer.transform(job) # fills the Nan with statistic values

[75.33333333 52.57142857 85.625     ]

       Computer  Marketing  Engineer
S_No
1     84.000000  55.000000      75.0
2     90.000000  53.000000      70.0
3     63.000000  52.571429      88.0
4     75.333333  50.000000      77.0
5     63.000000  41.000000      89.0
6     75.000000  54.000000      85.0
7     75.333333  51.000000      96.0
8     77.000000  64.000000     105.0

In [7]:
imputer.fit_transform(job)  # do both fit and transform simultaneously

       Computer  Marketing  Engineer
S_No
1     84.000000  55.000000      75.0
2     90.000000  53.000000      70.0
3     63.000000  52.571429      88.0
4     75.333333  50.000000      77.0
5     63.000000  41.000000      89.0
6     75.000000  54.000000      85.0
7     75.333333  51.000000      96.0
8     77.000000  64.000000     105.0

In [8]:
imputer = SimpleImputer(strategy = 'median').set_output(transform='pandas')
imputer.fit_transform(job)
print(imputer.statistics_)

[76.  53.  86.5]

In [9]:
imputer.fit_transform(job)

      Computer  Marketing  Engineer
S_No
1         84.0       55.0      75.0
2         90.0       53.0      70.0
3         63.0       53.0      88.0
4         76.0       50.0      77.0
5         63.0       41.0      89.0
6         75.0       54.0      85.0
7         76.0       51.0      96.0
8         77.0       64.0     105.0

In [10]:
# Excercise

In [11]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Cases\Chemical_Process_Data\ChemicalProcess.csv")
df.head()

,Yield,BiologicalMaterial01,BiologicalMaterial02,BiologicalMaterial03,BiologicalMaterial04,BiologicalMaterial05,BiologicalMaterial06,BiologicalMaterial07,BiologicalMaterial08,BiologicalMaterial09,...,ManufacturingProcess36,ManufacturingProcess37,ManufacturingProcess38,ManufacturingProcess39,ManufacturingProcess40,ManufacturingProcess41,ManufacturingProcess42,ManufacturingProcess43,ManufacturingProcess44,ManufacturingProcess45
0,38.00,6.25,49.58,56.97,12.74,19.51,43.73,100.0,16.66,11.44,...,0.019,0.5,3,7.2,NaN,NaN,11.6,3.0,1.8,2.4
1,42.44,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.019,2.0,2,7.2,0.1,0.15,11.1,0.9,1.9,2.2
2,42.03,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.018,0.7,2,7.2,0.0,0.00,12.0,1.0,1.8,2.3
3,41.42,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.018,1.2,2,7.2,0.0,0.00,10.6,1.1,1.8,2.1
4,42.49,7.47,63.33,72.25,14.02,17.91,54.66,100.0,18.22,12.80,...,0.017,0.2,2,7.3,0.0,0.00,11.0,1.1,1.7,2.1

In [12]:
df.isna().sum().sum()

np.int64(106)

In [13]:
from sklearn.impute import SimpleImputer

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error,r2_score

In [15]:
X = df.drop('Yield',axis=1)
y = df['Yield']

In [16]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26)
X_train.isnull().sum().sum(),X_test.isnull().sum().sum()

(np.int64(93), np.int64(13))

In [17]:
imputer = SimpleImputer(strategy='mean').set_output(transform='pandas')
X_trn_imp = imputer.fit_transform(X_train)
X_tst_imp = imputer.transform(X_test)
X_trn_imp.isnull().sum().sum(),X_tst_imp.isnull().sum().sum()

(np.int64(0), np.int64(0))

In [18]:
model = LinearRegression()
model.fit(X_trn_imp,y_train)

LinearRegression()

In [19]:
y_pred = model.predict(X_tst_imp)
print('R2 Score ->',r2_score(y_test,y_pred))
print('RMSE ->',root_mean_squared_error(y_test,y_pred))

R2 Score -> -7.299578219035819
RMSE -> 4.871093773818226

In [20]:
# Ridge
import numpy as np
from sklearn.linear_model import Ridge

alpha = np.linspace(0.001,10,20)
scores = []
for x in alpha:
    ridge = Ridge(alpha=x)
    ridge.fit(X_trn_imp,y_train)
    y_pred = ridge.predict(X_tst_imp)
    scores.append([x,r2_score(y_test,y_pred),root_mean_squared_error(y_test,y_pred)])
ridge_score = pd.DataFrame(scores,columns=['Alpha','R2 Score','RMSE']).sort_values('R2 Score',ascending=False)
ridge_score.head(2)

      Alpha  R2 Score      RMSE
4  2.106053 -2.459765  3.145008
5  2.632316 -2.466741  3.148177

In [21]:
# Lasso
from sklearn.linear_model import Lasso

alpha = np.linspace(0.001,10,20)
scores = []
for x in alpha:
    lasso = Lasso(alpha=x)
    lasso.fit(X_trn_imp,y_train)
    y_pred = lasso.predict(X_tst_imp)
    scores.append([x,r2_score(y_test,y_pred),root_mean_squared_error(y_test,y_pred)])
lasso_score = pd.DataFrame(scores,columns=['Alpha','R2 Score','RMSE']).sort_values('R2 Score',ascending=False)

C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.035920e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.011577e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.495603e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.048183e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.662752e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.742686e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.602239e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.415032e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.165782e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.932177e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.921053e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.274440e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.920271e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.810719e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.912961e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.203702e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.854816e-01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(

In [22]:
lasso_score.head(2)

       Alpha  R2 Score      RMSE
15  7.894947  0.325685  1.388449
14  7.368684  0.310737  1.403754

In [23]:
# Elastic Net
from sklearn.linear_model import ElasticNet

alpha = np.linspace(0.001,10,20)
l1 = np.linspace(0.001,1,20)
scores = []

for x in alpha:
    for l in l1:
        elastic_net = ElasticNet(alpha=x,l1_ratio=l)
        elastic_net.fit(X_trn_imp,y_train)
        y_pred = elastic_net.predict(X_tst_imp)
        scores.append([x,l,r2_score(y_test,y_pred),root_mean_squared_error(y_test,y_pred)])
elastic_net_score = pd.DataFrame(scores,columns=['Alpha','L1_Ratio','R2 Score','RMSE']).sort_values('R2 Score',ascending=False)

C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.933718e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.939665e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.945568e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.951422e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.957222e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.962965e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.968646e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.974257e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.979794e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.985247e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.990603e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.995878e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.001079e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.006196e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.011210e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.016134e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.020979e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.025879e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.030918e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.035920e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.076756e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.393597e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.636445e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.847484e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.023928e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.168369e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.239733e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.280905e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.324628e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.362559e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.385758e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.331563e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.278003e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.243077e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.223149e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.200217e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.157493e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.112249e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.063594e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.011577e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.634767e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.016834e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.275222e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.394713e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.434697e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.455254e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.353553e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.298428e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.200687e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.095194e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(

In [24]:
elastic_net_score.head(2)

       Alpha  L1_Ratio  R2 Score      RMSE
27  0.527263  0.369053  0.577195  1.099433
43  1.053526  0.158737  0.576039  1.100934

In [25]:
df.isnull().sum().sum()

np.int64(106)

In [26]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26)
X_train.isnull().sum().sum(),X_test.isnull().sum().sum()

(np.int64(93), np.int64(13))

In [27]:
imputer = SimpleImputer(strategy='median').set_output(transform='pandas')
X_trn_imp = imputer.fit_transform(X_train)
X_tst_imp = imputer.transform(X_test)
X_trn_imp.isnull().sum().sum(),X_tst_imp.isnull().sum().sum()

(np.int64(0), np.int64(0))

In [28]:
model = LinearRegression()
model.fit(X_trn_imp,y_train)

LinearRegression()

In [29]:
y_pred = model.predict(X_tst_imp)
print('R2 Score ->',r2_score(y_test,y_pred))
print('RMSE ->',root_mean_squared_error(y_test,y_pred))

R2 Score -> -5.420740111486076
RMSE -> 4.284410006348558

In [30]:
# Ridge
alpha = np.linspace(0.001,10,20)
scores = []
for x in alpha:
    ridge = Ridge(alpha=x)
    ridge.fit(X_trn_imp,y_train)
    y_pred = ridge.predict(X_tst_imp)
    scores.append([x,r2_score(y_test,y_pred),root_mean_squared_error(y_test,y_pred)])
ridge_score = pd.DataFrame(scores,columns=['Alpha','R2 Score','RMSE']).sort_values('R2 Score',ascending=False)
ridge_score.head(2)

      Alpha  R2 Score      RMSE
1  0.527263 -2.325319  3.083295
2  1.053526 -2.364063  3.101205

In [31]:
# Lasso
alpha = np.linspace(0.001,10,20)
scores = []
for x in alpha:
    lasso = Lasso(alpha=x)
    lasso.fit(X_trn_imp,y_train)
    y_pred = lasso.predict(X_tst_imp)
    scores.append([x,r2_score(y_test,y_pred),root_mean_squared_error(y_test,y_pred)])
lasso_score = pd.DataFrame(scores,columns=['Alpha','R2 Score','RMSE']).sort_values('R2 Score',ascending=False)

C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.044745e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.905927e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.471179e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.047568e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.695351e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.745051e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.593499e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394504e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.138755e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.690018e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.670856e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.024272e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.677857e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.583386e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.707814e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.025701e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.464600e-01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(

In [32]:
lasso_score.head(2)

       Alpha  R2 Score      RMSE
14  7.368684  0.324576  1.389590
15  7.894947  0.323347  1.390854

In [33]:
# Elastic Net
alpha = np.linspace(0.001,10,20)
l1 = np.linspace(0.001,1,20)

for x in alpha:
    for l in l1:
        elastic_net = ElasticNet(alpha=x,l1_ratio=l)
        elastic_net.fit(X_trn_imp,y_train)
        y_pred = elastic_net.predict(X_tst_imp)
        scores.append([x,l,r2_score(y_test,y_pred),root_mean_squared_error(y_test,y_pred)])
elastic_net_score = pd.DataFrame(scores,columns=['Alpha','L1_Ratio','R2 Score','RMSE']).sort_values('R2 Score',ascending=False)

C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.942222e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.948193e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.954122e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.960001e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.965827e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.971595e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.977302e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.982939e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.988499e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.993970e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.999347e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.004673e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.009920e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.015077e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.020167e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.025205e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.030188e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.035109e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.039964e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.044745e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.060806e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.367866e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.602981e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.807484e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.978708e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.136318e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.209797e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.251308e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.253906e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.228515e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.216279e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.200745e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.160017e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.120351e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.092662e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.074954e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.051473e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.004917e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.956462e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.905927e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.611006e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.975102e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.220572e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.332163e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.357249e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.303607e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.235877e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.167423e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.097020e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.989619e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(

In [34]:
elastic_net_score.head(2)

      Alpha  L1_Ratio  R2 Score  RMSE
0  0.001000 -7.962437  5.061876   NaN
2  1.053526 -4.017603  3.787448   NaN

# Using Pipeline

In [35]:
from sklearn.pipeline import Pipeline

ridge = Ridge(alpha=0.527263)
imputer = SimpleImputer(strategy = 'mean')
pipe = Pipeline([('Imp',imputer),('Rdg',ridge)])
pipe.fit(X_train,y_train)

Pipeline(steps=[('Imp', SimpleImputer()), ('Rdg', Ridge(alpha=0.527263))])

In [36]:
y_pred = pipe.predict(X_test)
print('R2 Score ->',r2_score(y_test,y_pred))
print('RMSE ->',root_mean_squared_error(y_test,y_pred))

R2 Score -> -2.693632628330699
RMSE -> 3.2495657459585994

# Elastic Net With Mean Imputer

In [37]:
# Elastic Net
imputer = SimpleImputer(strategy = 'mean')
alpha = np.linspace(0.001,10,20)
l1 = np.linspace(0.001,1,20)
scores = []

for x in alpha:
    for l in l1:
        el = ElasticNet(alpha = x, l1_ratio = l)
        pipe = Pipeline([('Imp',imputer),('Elc',el)])
        pipe.fit(X_train,y_train)
        y_pred = pipe.predict(X_test)
        scores.append([x,l,r2_score(y_test,y_pred),root_mean_squared_error(y_test,y_pred)])
elastic_net_score = pd.DataFrame(scores,columns=['Alpha','L1_Ratio','R2 Score','RMSE']).sort_values('R2 Score',ascending=False)

C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.933718e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.939665e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.945568e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.951422e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.957222e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.962965e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.968646e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.974257e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.979794e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.985247e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.990603e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.995878e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.001079e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.006196e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.011210e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.016134e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.020979e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.025879e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.030918e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.035920e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.076756e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.393597e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.636445e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.847484e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.023928e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.168369e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.239733e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.280905e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.324628e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.362559e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.385758e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.331563e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.278003e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.243077e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.223149e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.200217e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.157493e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.112249e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.063594e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.011577e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.634767e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.016834e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.275222e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.394713e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.434697e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.455254e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.353553e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.298428e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.200687e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.095194e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(

In [38]:
elastic_net_score.head(2)

       Alpha  L1_Ratio  R2 Score      RMSE
27  0.527263  0.369053  0.577195  1.099433
43  1.053526  0.158737  0.576039  1.100934

# Elastic Net With Median Imputer

In [ ]:
# Elastic Net
imputer = SimpleImputer(strategy = 'median')
alpha = np.linspace(0.001,10,20)
l1 = np.linspace(0.001,1,20)
scores = []

for x in alpha:
    for l in l1:
        el = ElasticNet(alpha = x, l1_ratio = l)
        pipe = Pipeline([('Imp',imputer),('Elc',el)])
        pipe.fit(X_train,y_train)
        y_pred = pipe.predict(X_test)
        scores.append([x,l,r2_score(y_test,y_pred),root_mean_squared_error(y_test,y_pred)])
elastic_net_score = pd.DataFrame(scores,columns=['Alpha','L1_Ratio','R2 Score','RMSE']).sort_values('R2 Score',ascending=False)

C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.942222e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.948193e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.954122e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.960001e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.965827e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.971595e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.977302e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.982939e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.988499e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.993970e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.999347e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.004673e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.009920e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.015077e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.020167e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.025205e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.030188e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.035109e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.039964e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.044745e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.060806e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.367866e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.602981e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.807484e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.978708e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.136318e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.209797e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.251308e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.253906e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.228515e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.216279e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.200745e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.160017e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.120351e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.092662e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.074954e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.051473e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.004917e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.956462e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.905927e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.611006e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.975102e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.220572e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.332163e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.357249e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.303607e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.235877e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.167423e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.097020e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.989619e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(

In [ ]:
elastic_net_score.head(2)